name: CI-demand

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: Vampire/setup-wsl@v6
      with:
          distribution: Ubuntu-24.04
          wsl-shell-command: bash -c "cd && bash --noprofile --norc -euo pipefail '{0}'"
    - shell: wsl-bash {0}
      run: |
        ls -al /
        lscpu
