name: CI-demand

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: Vampire/setup-wsl@v6
      with:
          distribution: Ubuntu-24.04
    - run: |
          ls -al
          lscpu
