name: CI-demand

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu
      - name: Run commands in WSL
        run: |
          wsl --exec bash -c "ls -la"
          wsl --exec bash -c "lscpu"
